export const GET_SHOP_CARDS = 'GET_SHOP_CARDS'
export const SET_SHOP_CARDS = 'SET_SHOP_CARDS'

export const GET_EVENT_CARDS = 'GET_EVENT_CARDS'
export const SET_EVENT_CARDS = 'SET_EVENT_CARDS'

export const GET_FIELD_CARDS = 'GET_FIELD_CARDS'
export const SET_FIELD_CARDS = 'SET_FIELD_CARDS'

export const GET_DIRECTION_LEADERS = 'GET_DIRECTION_LEADERS'
export const SET_DIRECTION_LEADERS = 'SET_DIRECTION_LEADERS'

export const GET_SHOPPER_CARDS = 'GET_SHOPPER_CARDS'
export const SET_SHOPPER_CARDS = 'SET_SHOPPER_CARDS'

export const GET_STRUCTURE_PREVIEWS = 'GET_STRUCTURE_PREVIEWS'
export const SET_STRUCTURE_PREVIEWS = 'SET_STRUCTURE_PREVIEWS'

export const GET_AUTH = 'GET_AUTH'
export const SET_AUTH = 'SET_AUTH'
export const LOG_OUT = 'LOG_OUT'

export const GET_REG = 'GET_REG'
export const SET_REG = 'SET_REG'

export const SET_LOADING = 'SET_LOADING'
export const SET_ERROR = 'SET_ERROR'
